/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package p2pnode-R3 */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 6 "exports.go"

#include <stdlib.h>
#include <string.h>

typedef struct {
	int success;
	char* message;
	char* node_id;
} P2PInitResult;

typedef struct {
	char* status;      // JSON status response
	char* peers;       // JSON peers array
	char* node_id;
	int api_port;
	int control_port;
} P2PStatus;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// P2P_Init initializes the p2p node with the given parameters.
// Returns 0 on success, non-zero on error.
// forceNewEnv: if 1, recreate env.enc even if it exists (like --new-net)
//
extern __declspec(dllexport) int P2P_Init(char* envPass, int apiPort, int controlPort, char* mcGroup, int mcPort, char* keySaverUrl, int forceNewEnv);

// P2P_Start starts the p2p node services (discovery, HTTP servers).
// Returns 0 on success.
//
extern __declspec(dllexport) int P2P_Start(void);

// P2P_Stop gracefully stops all p2p services.
//
extern __declspec(dllexport) void P2P_Stop(void);

// P2P_GetStatus returns JSON status. Caller must free the returned string.
//
extern __declspec(dllexport) char* P2P_GetStatus(void);

// P2P_GetPeers returns JSON array of peers. Caller must free the returned string.
//
extern __declspec(dllexport) char* P2P_GetPeers(void);

// P2P_GetNodeID returns the node ID. Caller must free.
//
extern __declspec(dllexport) char* P2P_GetNodeID(void);

// P2P_GetPublicKey returns base64 encoded public key. Caller must free.
//
extern __declspec(dllexport) char* P2P_GetPublicKey(void);

// P2P_FreeString frees a string returned by this library.
//
extern __declspec(dllexport) void P2P_FreeString(char* s);

// P2P_IsRunning returns 1 if node is running, 0 otherwise.
//
extern __declspec(dllexport) int P2P_IsRunning(void);

#ifdef __cplusplus
}
#endif
